// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: broadcast.proto

package broadcasts

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BroadcasterClient is the client API for Broadcaster service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BroadcasterClient interface {
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (Broadcaster_SubscribeClient, error)
}

type broadcasterClient struct {
	cc grpc.ClientConnInterface
}

func NewBroadcasterClient(cc grpc.ClientConnInterface) BroadcasterClient {
	return &broadcasterClient{cc}
}

func (c *broadcasterClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (Broadcaster_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &Broadcaster_ServiceDesc.Streams[0], "/broadcast.Broadcaster/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &broadcasterSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Broadcaster_SubscribeClient interface {
	Recv() (*BroadcastMessage, error)
	grpc.ClientStream
}

type broadcasterSubscribeClient struct {
	grpc.ClientStream
}

func (x *broadcasterSubscribeClient) Recv() (*BroadcastMessage, error) {
	m := new(BroadcastMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BroadcasterServer is the server API for Broadcaster service.
// All implementations must embed UnimplementedBroadcasterServer
// for forward compatibility
type BroadcasterServer interface {
	Subscribe(*SubscribeRequest, Broadcaster_SubscribeServer) error
	mustEmbedUnimplementedBroadcasterServer()
}

// UnimplementedBroadcasterServer must be embedded to have forward compatible implementations.
type UnimplementedBroadcasterServer struct {
}

func (UnimplementedBroadcasterServer) Subscribe(*SubscribeRequest, Broadcaster_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedBroadcasterServer) mustEmbedUnimplementedBroadcasterServer() {}

// UnsafeBroadcasterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BroadcasterServer will
// result in compilation errors.
type UnsafeBroadcasterServer interface {
	mustEmbedUnimplementedBroadcasterServer()
}

func RegisterBroadcasterServer(s grpc.ServiceRegistrar, srv BroadcasterServer) {
	s.RegisterService(&Broadcaster_ServiceDesc, srv)
}

func _Broadcaster_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BroadcasterServer).Subscribe(m, &broadcasterSubscribeServer{stream})
}

type Broadcaster_SubscribeServer interface {
	Send(*BroadcastMessage) error
	grpc.ServerStream
}

type broadcasterSubscribeServer struct {
	grpc.ServerStream
}

func (x *broadcasterSubscribeServer) Send(m *BroadcastMessage) error {
	return x.ServerStream.SendMsg(m)
}

// Broadcaster_ServiceDesc is the grpc.ServiceDesc for Broadcaster service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Broadcaster_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "broadcast.Broadcaster",
	HandlerType: (*BroadcasterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _Broadcaster_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "broadcast.proto",
}
